-- [SCHEMA] Tabela para o Mural de Mensagens do Convite
create table mural_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ativar políticas de segurança básicas
alter table mural_messages enable row level security;

-- Permitir leitura para todos (anônimos podem ver as mensagens)
create policy "Permitir leitura pública"
  on mural_messages for select
  using ( true );

-- Permitir inserção para todos (convidados inserem mensagens)
create policy "Permitir inserção de mensagens"
  on mural_messages for insert
  with check ( true );
